// ===== Text animations =====
export { Typewriter } from './animations/text/Typewriter'
export { Wave } from './animations/text/Wave'
export { Scramble } from './animations/text/Scramble'
export { Blink } from './animations/text/Blink'
export { Highlight } from './animations/text/Highlight'
export { Underline } from './animations/text/Underline'
export { Strike } from './animations/text/Strike'
export { BounceIn } from './animations/text/BounceIn'
export { FadeWord } from './animations/text/FadeWord'
export { RevealMask } from './animations/text/RevealMask'
export { Counter } from './animations/text/Counter'
export { Sparkle } from './animations/text/Sparkle'
export { Shuffle } from './animations/text/Shuffle'
export { Marquee } from './animations/text/Marquee'
export { Rotator } from './animations/text/Rotator'
export { Decode } from './animations/text/Decode'
export { Capitalize } from './animations/text/Capitalize'
export { Glitch } from './animations/text/Glitch'
export { Neon } from './animations/text/Neon'

// ===== View animations =====
export { Breathe } from './animations/view/Breathe'
export { Float } from './animations/view/Float'
export { FadeIn } from './animations/view/FadeIn'
export { PaperPlane } from './animations/view/PaperPlane'
export { ThanosSnap } from './animations/view/ThanosSnap'
export { FireBurn } from './animations/view/FireBurn'
export { TearReveal } from './animations/view/TearReveal'
export { Pop } from './animations/view/Pop'
export { Drop } from './animations/view/Drop'
export { Spin } from './animations/view/Spin'
export { Tilt } from './animations/view/Tilt'
export { Wobble } from './animations/view/Wobble'
export { JellyPress } from './animations/view/JellyPress'
export { Magnetic } from './animations/view/Magnetic'
export { Shake } from './animations/view/Shake'
export { Wiggle } from './animations/view/Wiggle'
export { Pulse } from './animations/view/Pulse'
export { RubberBand } from './animations/view/RubberBand'
export { Heart } from './animations/view/Heart'
export { Flash } from './animations/view/Flash'
export { Glow } from './animations/view/Glow'
export { Sparkles } from './animations/view/Sparkles'
export { Stamp } from './animations/view/Stamp'
export { Ripple } from './animations/view/Ripple'
export { FlipCard } from './animations/view/FlipCard'
export { Tilt3D } from './animations/view/Tilt3D'
export { Shatter } from './animations/view/Shatter'

// ===== Background animations =====
export { Aurora } from './animations/background/Aurora'
export { GradientShift } from './animations/background/GradientShift'
export { Stars } from './animations/background/Stars'
export { Snow } from './animations/background/Snow'
export { Rain } from './animations/background/Rain'
export { Bubbles } from './animations/background/Bubbles'
export { Fireflies } from './animations/background/Fireflies'
export { Waves } from './animations/background/Waves'
export { MatrixRain } from './animations/background/MatrixRain'

// ===== Transition in/out =====
export { CrossFade } from './animations/transition/CrossFade'
export { Zoom } from './animations/transition/Zoom'
export { Iris } from './animations/transition/Iris'
export { Curtain } from './animations/transition/Curtain'
export { Pixelate } from './animations/transition/Pixelate'
export { Vortex } from './animations/transition/Vortex'
export { Materialize } from './animations/transition/Materialize'
export { Mosaic } from './animations/transition/Mosaic'

// ===== Gesture =====
export { TapFeedback } from './animations/gesture/TapFeedback'
export { LongPressGrow } from './animations/gesture/LongPressGrow'
export { DoubleTapHeart } from './animations/gesture/DoubleTapHeart'
export { SwipeReveal } from './animations/gesture/SwipeReveal'

// ===== Decoration =====
export { Check } from './animations/decoration/Check'
export { Cross } from './animations/decoration/Cross'
export { Star } from './animations/decoration/Star'
export { Badge } from './animations/decoration/Badge'
export { Notification } from './animations/decoration/Notification'
export { Confetti } from './animations/decoration/Confetti'
export { LikeButton } from './animations/decoration/LikeButton'
export { EmojiBurst } from './animations/decoration/EmojiBurst'
export { RatingStars } from './animations/decoration/RatingStars'
export { Coins } from './animations/decoration/Coins'

// ===== Charts =====
export { ProgressRing } from './animations/chart/ProgressRing'
export { AnimatedBar } from './animations/chart/AnimatedBar'
export { Sparkline } from './animations/chart/Sparkline'
export { LineChart } from './animations/chart/LineChart'
export { BarChart } from './animations/chart/BarChart'
export { Gauge } from './animations/chart/Gauge'
